import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Header } from '@/components/layout';
import SWRProvider from '@/components/SWRProvider';
import '../styles/globals.css';
import { ToastContainer } from 'react-toastify';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Reporter App',
  description: 'Generated by Helen',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='ko'>
      <body className={inter.className}>
        <SWRProvider>
          <Header />
          {children}
          <ToastContainer />
        </SWRProvider>
      </body>
    </html>
  );
}
